// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgheiS9zK2rMv8rREt6Nscg3c3NNI2kQY',
    appId: '1:1085489363675:web:03dd44f959dd658d596afe',
    messagingSenderId: '1085489363675',
    projectId: 'projetinho-c043f',
    authDomain: 'projetinho-c043f.firebaseapp.com',
    databaseURL: 'https://projetinho-c043f-default-rtdb.firebaseio.com',
    storageBucket: 'projetinho-c043f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9MtMTPl9jXQM8aGogzM37-Ag-Dc3i6D0',
    appId: '1:1085489363675:android:d7cfb6048ec4c6d1596afe',
    messagingSenderId: '1085489363675',
    projectId: 'projetinho-c043f',
    databaseURL: 'https://projetinho-c043f-default-rtdb.firebaseio.com',
    storageBucket: 'projetinho-c043f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWf4arDx8U2Wt-4X1BNkMUYrLEKJoRFG8',
    appId: '1:1085489363675:ios:94b9a04d6e0f7ba2596afe',
    messagingSenderId: '1085489363675',
    projectId: 'projetinho-c043f',
    databaseURL: 'https://projetinho-c043f-default-rtdb.firebaseio.com',
    storageBucket: 'projetinho-c043f.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWf4arDx8U2Wt-4X1BNkMUYrLEKJoRFG8',
    appId: '1:1085489363675:ios:72c6603bff05d698596afe',
    messagingSenderId: '1085489363675',
    projectId: 'projetinho-c043f',
    databaseURL: 'https://projetinho-c043f-default-rtdb.firebaseio.com',
    storageBucket: 'projetinho-c043f.appspot.com',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );
}
