// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdX7FFyKzHYzjtRer-ni6amjW_ZBj81g',
    appId: '1:308355020175:web:59cae7f1531e5a958947fa',
    messagingSenderId: '308355020175',
    projectId: 'caterddd',
    authDomain: 'caterddd.firebaseapp.com',
    databaseURL: 'https://caterddd-default-rtdb.firebaseio.com',
    storageBucket: 'caterddd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBD4fGXFU9py9wRg8l-fNlpVBax35bZtQ',
    appId: '1:308355020175:android:a533be6c16337f138947fa',
    messagingSenderId: '308355020175',
    projectId: 'caterddd',
    databaseURL: 'https://caterddd-default-rtdb.firebaseio.com',
    storageBucket: 'caterddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUwh6aYvQi_9VKc1feNVKp20oJRSH-rs',
    appId: '1:581039158937:ios:895789374ecad6b2122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqUwh6aYvQi_9VKc1feNVKp20oJRSH-rs',
    appId: '1:581039158937:ios:895789374ecad6b2122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjdX7FFyKzHYzjtRer-ni6amjW_ZBj81g',
    appId: '1:308355020175:web:bea6d9cb97e8e0198947fa',
    messagingSenderId: '308355020175',
    projectId: 'caterddd',
    authDomain: 'caterddd.firebaseapp.com',
    databaseURL: 'https://caterddd-default-rtdb.firebaseio.com',
    storageBucket: 'caterddd.appspot.com',
  );

}