// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUldRq3rk-Ac_Fno_dtCL5P24W6VCmbQ',
    appId: '1:581039158937:web:27aabdb75c638250122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    authDomain: 'projetoaplicado-2f74d.firebaseapp.com',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3o1f21MnnDjlza5l__izhr68Ur5LYbys',
    appId: '1:581039158937:android:6e9527f12625e2e6122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUwh6aYvQi_9VKc1feNVKp20oJRSH-rs',
    appId: '1:581039158937:ios:895789374ecad6b2122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqUwh6aYvQi_9VKc1feNVKp20oJRSH-rs',
    appId: '1:581039158937:ios:895789374ecad6b2122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUldRq3rk-Ac_Fno_dtCL5P24W6VCmbQ',
    appId: '1:581039158937:web:0111db30f3a3b86a122a08',
    messagingSenderId: '581039158937',
    projectId: 'projetoaplicado-2f74d',
    authDomain: 'projetoaplicado-2f74d.firebaseapp.com',
    storageBucket: 'projetoaplicado-2f74d.appspot.com',
  );

}